# Generated by Django 3.0.2 on 2020-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200321_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='products.OrderItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Dry cakes', 'Dry Cakes'), ('Cookies', 'Cookies'), ('Cakes', 'Cakes')], max_length=15),
        ),
    ]
