# Generated by Django 3.0.2 on 2020-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200323_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cookies', 'Cookies'), ('Dry cakes', 'Dry Cakes'), ('Cakes', 'Cakes')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], max_length=15),
        ),
    ]
